# Generated by Django 3.0.7 on 2020-07-21 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0003_auto_20200721_0628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='h9.jpg', upload_to=''),
        ),
    ]
