# Generated by Django 3.0.7 on 2020-08-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200721_0655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='h5.jpg', upload_to=''),
        ),
    ]
