# Generated by Django 3.0.7 on 2020-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20200808_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='h7.jpg', upload_to=''),
        ),
    ]
